### ISSUE TITLE
マップ依存のボス討伐に関して

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#1]
kurosemi 
Tconのハートの器の黄色い方とか大丈夫かな？難易度的には大した影響はなさそうだけど黄昏のナーガが黄ハート落とすので乱獲されると黄昏の攻略が面倒になる

**Comment by karekusa** [comment]
botaniaのボスを倒せば黄色いハートが手に入る
黄昏で乱獲が起こった場合は全体責任ということで?いいのか?

**Comment by a0n0** [comment]
黄昏マップは再生成

その条件タイミングは未決定
