### ISSUE TITLE
飛行に関して

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#11]
魔法使いに関しては不便な飛行はあり

・TCのソーモスタティックハーネス
・ウィッチリーのホウキ

ぎりあり

**Comment by kurosemi** [comment]
ボタニアの飛行装備の解説（コピペ
・Flugel Tiara
装備すると空腹ゲージの上に現れる飛行ゲージ？を消費してクリエイティブ飛行が出来るようになる
フルゲージから効果が切れるまでおよそ30秒、地上にいるとゲージは回復していく
ゼロから最大値までの回復に60秒ほど
色々あるバリエーションは外見的な違いだけで中身の性能はどれも同じ
30秒間？飛ぶことで22035マナを消費する、Mana tabletの最大容量は50万マナ
飛行ゲージが1個以上残っている場合落下ダメージを受けない

**Comment by a0n0** [comment]
魔術に残してても良さそうって感じするけどね。　飛行の話題逸れるけどbotania dice of fate消しとこうって話になってたな。そういや。

**Comment by kurosemi** [comment]
連続飛行30秒だけみたいだしアリだと思う
使用感試してみる必要はありそうだけども

**Comment by kurosemi** [comment]
クリエイティブで試してみたところボタニアの飛行は結構使いごこちよさそう
ずっと飛んでられる訳じゃないけど
