### ISSUE TITLE
IC2をいれますよ　制限アイテムについて

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#13]
消すべきアイテムについて知識を授けてください

基準は
飛行、過剰生産、スポナー系、AOAを形骸化させる戦闘力とか　かな

thermal expansionくらいの能力感をイメージしてます。

**Comment by a0n0** [comment]
discord議論より

jetpack  
クアンタム
マイニングレーザー

他にももしあれば。

**Comment by a0n0** [comment]
vending いけたらこのお話は無しに。

**Comment by karekusa** [comment]
vending の結果がここにはないけど､OKでいいのかい?

**Comment by a0n0** [comment]
OKです　無し。
