### ISSUE TITLE
witcheryの大釜でのネザーウォート作成が失敗する事案

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#14]
kurosemi 
kurosemi commented 2 hours ago
タイトル通り。
魔力も参照範囲も足りているのに失敗する。
一瞬成功エフェクトが出たのでもう少し検証の必要あり？

 kurosemi
kurosemi commented 11 minutes ago
クリエイティブのシングルで試したところ成功

a0n0
検討つかないな.......
singleでいけてmultiでできないってpluginの影響ってパターンが多いけどそんな項目は思いつかない。謎度高め。もう少しあの手この手で検証続けてほしい　こっちも調べとく。

**Comment by kurosemi** [comment]
マルチでも成功しました
単純にMODの仕様の可能性あり（おそらく魔力不足か何かだと思われるが、正確な原因は不明）

**Comment by a0n0** [comment]
おりょ　OKです！
