### ISSUE TITLE
ExU tier制限に関して

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#2]
Kassi [14日前]
ジョウロ
シジル
カーズドアース
扇風機

kurosemi [14日前]
カースドアースはシジルの儀式で作るから間接的に消える？ （編集済み）

Kassi [14日前]
せやな

Kassi [14日前]
てかシジル消したら大体解決

Kassi [14日前]
扇風機はまあどうしよっか、ってところ

kurosemi [14日前]
ジョウロは農業（特にアグリ）の難易度を上げたいなら消すべき
ALL10種が簡単に作れてもいいなら消さなくてもいい

ふま [14日前]
後はクアーリーも消す予定だったよね

Kassi [14日前]
せやな

kurosemi [14日前]
上位如雨露はシジルで間接的に消える

ふま [14日前]
発電機一式

Kassi [14日前]
それもあったな
あとはパイプのアップグレード(スピードとスタックのみ)消しとく？

ふま [14日前]
エンダー送信機と受信機がよく分からんのやけど、これアイテムテレポートだっけ？これもやばいよね？

Kassi [14日前]
そいつは触ったことないなあ

ふま [14日前]
金床で名前を１とかしてチェンネル設定して輸送らしいんだけど、検証したけど使い方が分からなかった＾＾；
テレポートてきなのなら、規制かティアにいれないといけないよねーって

kurosemi [14日前]
めんどくさいから規制でいいんじゃね(｡∀゜)

a0n0 [14日前]
うん　迷ったら消そうw

a0n0 [14日前]
建材　ゴミ箱　サウンドマフラー　マグナムトーチ類　パイプ類　建築支援系ブロック　くらいかな　俺が把握してるので残したいのは。　パイプアップグレードもべつにtier制限なしでよくね？って思うけど　やっぱ違和感あるくらい高性能なの？

kurosemi [14日前]
EXUのパイプはアップグレードすれば他のMODのパイプの比じゃない速度で運搬できる

a0n0 [13日前]
パイプの速度、が「mod攻略が手段ではなく、目的化してしまう現象」に直結しないような気がするがどうだろう。自分がパイプの速度を気にしてプレイした事がないのでイメージできない （編集済み）

kurosemi [13日前]
まぁ直結はしなさそうですね

Kassi [13日前]
まあ自動化ライン生産する上でノータイムでくるのいいよねってところだね

a0n0 [13日前]
自動化ラインが快適ってのが　経済とか　建築の盛り上がりに繋がる感じにつながればいいね

exuのパイプ関連を無属性tier4とかかなあ

**Comment by a0n0** [comment]
a0n0 [11日前]
items {
   B:DivisionSigilEnabled=true->false
   B:DestructionPickaxeEnabled=true->false
   B:ErosionShovelEnabled=true->false
   B:EthericSwordEnabled=true->false
   B:HealingAxeEnabled=true->false
   B:TemporalHoeEnabled=true->false
   B:PrecisionShearsIdEnabled=true->false

   B:AngelRingEnabled=true->false
   B:SoulEnabled=true->false
   B:WateringCanEnabled=true->false

   B:UpgradeNodeEnabled=true->false

   B:UnstableIngotEnabled=true->false
}

blocks {
   B:EnderCollectorEnabled=true->false

   B:CursedEarthEnabled=true->false
   B:EnderLilyEnabled=true->false(検討が必要かも？)

   B:Generator64Enabled=true->false
   B:Generator8Enabled=true->false
   B:GeneratorEnabled=true->false

   B:SpikeEnabled=true->false
   B:SpikeDiamondEnabled=false
   B:SpikeGoldEnabled=true->false
   B:SpikeWoodEnabled=true->false

   B:TransferNodeEnabled=true->false
   B:TransferNodeRemoteEnabled=true->false

   B:MicroBlocksEnabled=true->false
   B:UnstableIngotEnabled=true->false
}

recipes {
   B:disableQEDIngotSmeltRecipes=false->true
   
   B:disableBuildersWandRecipe=true
}


a0n0 [11日前]
↑B:disableBuildersWandRecipe=false->true

by honon

**Comment by a0n0** [comment]
一度これ　日本語でリスト化せんとわからんな

**Comment by karekusa** [comment]
ExUはとりあえず全部規制してから必要な部分をリストから消していくホワイトリスト式のほうがいいのでは?

**Comment by a0n0** [comment]
俺もそう思うけどケーブル類とか結構多いよね　誰かに任せてしまいたい

**Comment by c2FUMAc2** [comment]
items {
B:DivisionSigilEnabled=true->false         　 除算のシジル
B:DestructionPickaxeEnabled=true->false		　破壊のツルハシ
B:ErosionShovelEnabled=true->false			　侵食のショベル
B:EthericSwordEnabled=true->false			　天上の剣
B:HealingAxeEnabled=true->false				　癒しの斧
B:TemporalHoeEnabled=true->false			　反転するクワ?
B:PrecisionShearsIdEnabled=true->false		　精密ばさみ

B:AngelRingEnabled=true->false				　エンジェルリング
B:SoulEnabled=true->false					　魂の破片？
B:WateringCanEnabled=true->false			　ジョウロ
B:UpgradeNodeEnabled=true->false			　アップグレードノード
B:UnstableIngotEnabled=true->false			　不安定なインゴット		
}

blocks {
B:EnderCollectorEnabled=true->false			　エンダーコレクター
B:CursedEarthEnabled=true->false			　呪われた土壌
B:EnderLilyEnabled=true->false(検討が必要かも？)エンダーリリーの種
B:Generator64Enabled=true->false			　64倍発電機
B:Generator8Enabled=true->false				　8倍発電機
B:GeneratorEnabled=true->false				　発電機
B:SpikeEnabled=true->false					　スパイク
B:SpikeDiamondEnabled=false					　ダイヤモンドスパイク
B:SpikeGoldEnabled=true->false				　金のスパイク
B:SpikeWoodEnabled=true->false				　木のスパイク
B:TransferNodeEnabled=true->false			　搬送ノード
B:TransferNodeRemoteEnabled=true->false		　回収ノード
B:MicroBlocksEnabled=true->false			 マイクロブロック
B:UnstableIngotEnabled=true->false			　不安定なインゴットブロック		　
}

recipes {
B:disableQEDIngotSmeltRecipes=false->true　　　QEDで作れるもののレシピ無効？
B:disableBuildersWandRecipe=true　　　         ビルダーズワンドのレシピ無効？
}
B:disableBuildersWandRecipe=false->true　　　　ビルダーズワンドのレシピ無効？

**Comment by a0n0** [comment]
おっし　ここ確定させていこう

現在のExU廃止予定アイテムたち
除算のシジル
破壊のツルハシ
侵食のショベル
B:EthericSwordEnabled=true->false	　天上の剣
B:HealingAxeEnabled=true->false	　癒しの斧
B:TemporalHoeEnabled=true->false	　反転するクワ?
B:PrecisionShearsIdEnabled=true->false	　精密ばさみ

B:AngelRingEnabled=true->false	　エンジェルリング
B:SoulEnabled=true->false	　魂の破片？
B:WateringCanEnabled=true->false	　ジョウロ
B:UpgradeNodeEnabled=true->false	　アップグレードノード
B:UnstableIngotEnabled=true->false	　不安定なインゴット
}

blocks {
B:EnderCollectorEnabled=true->false	　エンダーコレクター
B:CursedEarthEnabled=true->false	　呪われた土壌
B:EnderLilyEnabled=true->false(検討が必要かも？)エンダーリリーの種
B:Generator64Enabled=true->false	　64倍発電機
B:Generator8Enabled=true->false	　8倍発電機
B:GeneratorEnabled=true->false	　発電機
B:SpikeEnabled=true->false	　スパイク
B:SpikeDiamondEnabled=false	　ダイヤモンドスパイク
B:SpikeGoldEnabled=true->false	　金のスパイク
B:SpikeWoodEnabled=true->false	　木のスパイク
B:TransferNodeEnabled=true->false	　搬送ノード
B:TransferNodeRemoteEnabled=true->false	　回収ノード
B:MicroBlocksEnabled=true->false	マイクロブロック
B:UnstableIngotEnabled=true->false	　不安定なインゴットブロック	　
}

recipes {
B:disableQEDIngotSmeltRecipes=false->true　　　QEDで作れるもののレシピ無効？
B:disableBuildersWandRecipe=true　　　 ビルダーズワンドのレシピ無効？
}
B:disableBuildersWandRecipe=false->true　　　　ビルダーズワンドのレシピ無効？

**Comment by a0n0** [comment]
おっし　ここ確定させていこう

現在のExU廃止予定アイテムたち

DivisionSigil 除算のシジル
DestructionPickaxe	破壊のツルハシ
ErosionShovel 侵食のショベル
EthericSword 天上の剣
HealingAxe　癒しの斧
TemporalHoe　反転するクワ？
PrecisionShearsId　精密ばさみ

AngelRing　エンジェルリング
Sou　魂の破片？
WateringCan　ジョウロ
UpgradeNode　アップグレードノード
UnstableIngot　不安定なインゴット

EnderCollector　エンダーコレクター
CursedEarth　呪われた土壌
EnderLily(検討が必要かも？)エンダーリリーの種
Generator64　64倍発電機
Generator8　8倍発電機
Generator　発電機
Spike　スパイク
SpikeDiamond　ダイヤモンドスパイク
SpikeGold　金のスパイク
SpikeWood　木のスパイク
TransferNode　搬送ノード
TransferNodeRemote　回収ノード
MicroBlocks　マイクロブロック
UnstableIngot　不安定なインゴットブロック	　



B:disableQEDIngotSmeltRecipes=false->true　　　QEDで作れるもののレシピ無効？
B:disableBuildersWandRecipe=false->true　　　　ビルダーズワンドのレシピ無効？


wikiとか見て
https://www26.atwiki.jp/minecraft/pages/1466.html#id_9b6eb647

これは消さなくていいでしょ！とかここに無いけどこれはまずい！

とか　discordでもここでもいいので意見待ってます。

**Comment by a0n0** [comment]
zsこっちで確認しようか

// ExtraUtilities

angelRing
unstableingot
nodeUpgrade
watering_can

generator
spike
spike_base_gold
spike_base_diamond
decorativeBlock1:11
peaceful_table_top
pipes
extractor_base
nodeUpgrade

builderswand
erosionShovel
destructionpickaxe
defoliageAxe
temporalHoe
ethericsword
shears

//SoulEnabled=true>false - cfg
//CursedEarthEnabled=true>false - cfg
//MicroBlocksEnabled=true>false -cfg
//DivisionSigilEnabled=true>false - cfg

個人的な意見でよいので聞かせてください～
