### ISSUE TITLE
Random Thingsついて

### ISSUE THREAD

**Issue by c2FUMAc2** [finalcity/SERVER_dev#32]
・Spirit Binderスポナー移動
・Fertilized Dirt　成長が早くなる。　農業にいれたほうがいいんじゃないか？
・Magnetic Force
他のプレイヤーの場所にテレポートするためのアイテム。マルチ用。
プレイヤー名をクリックすると、これを1つ消費してその場所に飛べる。 

材料：エンダーパール×1、エメラルド×1、紙×1
・Whitestone
ダンジョンチェストから入手可能。
満月の夜に、月が最も高いところにある状態でこれを持って外にいるとプレイヤーがパーティクルに覆われ、充電される。
充電された(Charged)状態では、持っているだけでプレイヤーの死を防げ、死の回避後にはいくつかのバフがかかる。
その後、エネルギーはすべて消費される。 

・Bloodstone
前述のWhitestoneを充電された状態でブラッドムーン時に屋外で投げ捨てる(Qキー)と作れる。
こちらを充電するには、モブを殺す必要がある。 
充電量に応じて、プレイヤーの体力を自動で回復させるが、これを持った状態で死ぬと、充電量は0になる。

これらのアイテムをどうするか
Spirit Binder・Magnetic Force ･ whitestone ･ bloodstoneをとりあえず、共通排除にとりま入れた。Fertilized Dirt保留状態。

他にも怪しいアイテムあるかも・・・
http://windworld.doorblog.jp/archives/22328743.html

**Comment by karekusa** [comment]
### 共通排除
 1. Spirit Binder
 2. Magnetic Force 
 3. whitestone 
 4. bloodstone 
以上4つのアイテムは共通排除 として対応した
### Fertilized Dirt 
 - 農家用として 対応した
 - 表記の上では成長が早いとあるが､watering can(ExtreUtilities) を使用した際の速度はバニラの土と変わらなかった

**Comment by c2FUMAc2** [comment]
spectre装備一式、AOA装備より強かったため排除項目にいれました。
