### ISSUE TITLE
鉱石分布をいじるってどうなのよ

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#6]
a0n0 [11日前]
どこ掘っても地下は大体一緒ってのはマップには優しいけど、分布が偏ってる事で交易とか冒険採掘みたいな要素が上がるから気になってるのだ

**Comment by a0n0** [comment]
https://minecraft.curseforge.com/projects/customoregen/files/2335337

**Comment by c2FUMAc2** [comment]
今までだとY10掘ればいいって感じだったので、y10,y30y50付近でしか取れない鉱石とか合ったら面白さそうですね。

**Comment by a0n0** [comment]
だね〜

あと、この地方では鉄ばっかりだけど　こっちは金がめっちゃある　みたいなのも楽しそう

重い疑惑がネック。
あとは全く扱った事が無い技術だから俺的には多分手が回らないので実現するとすれば実現を強く望む人が現れてシステム構築を進めてくれるパターンでしかなさそうかな。

**Comment by karekusa** [comment]
鉱石分布をいじることより､その後の混乱に対応するコストのほうが重くなると判断が出ました
