### ISSUE TITLE
導入検討　ObsAoA

### ISSUE THREAD

**Issue by a0n0** [finalcity/SERVER_dev#7]
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2753878-obsaoa-an-add-on-for-advent-of-ascension

**Comment by karekusa** [comment]
このmodがどれだけ好きかおしえて?
(意訳:どんなmodなの? 軽く噛み砕いて教えて欲しい)

**Comment by a0n0** [comment]
めちゃめちゃ好き

aoaのaddon。

aoaの追加ブロックがmicroforgeに対応したり、aoaBGMがレコードアアイテムとして追加される。マストバイ！

**Comment by c2FUMAc2** [comment]
ボス倒したらﾚｺｰｰｰｰｰｰｰｰｰｰｰﾄﾞ！！！！ボス毎にレコードが設定してあるのかな！？
これはAoAをティアに組み込める予感！！！！
